name: Auto update

on:
  schedule:
  - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh

    env:
      ProjectName: Dalamud.Plugin.SkipCutscene

    steps:
      - uses: actions/create-github-app-token@v2
        id: generate-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@v4

      - name: Compare Dalamud SDK version
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          $dalamudVersion = [Management.Automation.SemanticVersion](`
            Invoke-RestMethod `
              https://raw.githubusercontent.com/goatcorp/Dalamud.NET.Sdk/refs/heads/master/Dalamud.NET.Sdk/Sdk/SdkPackageVersions.props).`
            Project.`
            PropertyGroup.`
            PackageVersion_Dalamud_NET_Sdk

          $projectPath = "${env:GITHUB_WORKSPACE}/src/${env:ProjectName}/${env:ProjectName}.csproj"
          $projectXml = [xml](Get-Content -Raw $projectPath)
          $sdk, $currentVersion = $projectXml.Project.Sdk.Split('/')

          if ($dalamudVersion -gt $currentVersion) {
            $projectXml.Project.Sdk = [string]::join('/', $sdk, $dalamudVersion)
            $projectXml.Save($projectPath)
          }

          if (git diff) {
            git config --global user.name 'fa274771-c46d-4807-8c62-b98e1c75b85c'
            git config --global user.email 'fa274771-c46d-4807-8c62-b98e1c75b85c@users.noreply.github.com'

            $branch = "update/dalamud-sdk-$dalamudVersion"
            $message = "Update to $sdk/$dalamudVersion"
            git checkout -b $branch
            git commit -a -m $message
            git push --set-upstream origin $branch

            $pullRequestUri = gh pr create --fill
            gh pr merge `
              --auto `
              --squash `
              --delete-branch `
              $pullRequestUri
          }