name: CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v2

      # - name: Setup Nuget
      #   uses: nuget/setup-nuget@v1
      #   with:
      #      nuget-version: latest

      # - name: Restore Nuget Packages
      #   run: nuget restore SkipCutscene.sln

      - name: Download dalamud 
        run: |
          New-Item `
            -Path /tmp/
            -ItemType Directory `
            -Force
            
          Invoke-RestMethod https://goatcorp.github.io/dalamud-distrib/latest.zip `
            -Outfile /tmp/dalamud.zip

          Extract-Archive /tmp/dalamud.zip `
            -DestinationPath /tmp/dalamud

      - name: Build
        run: dotnet build 
          $Env:GITHUB_WORKSPACE\SkipCutscene.sln 
          /p:Configuration=Pack

      - name: debug
        run: |
          Write-Host 'event name is: ${{ github.event_name }}'
          Write-Host 'event type is: ${{ github.event.action }}'

    #  - name: Publish
    #    if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
    #    env:
    #      GITHUB_TOKEN: ${{ github.TOKEN }}
    #    run: |
    #      cd ${{github.workspace}}
    #      gh release upload ${{ github.event.release.tag_name }} feedmd-win-x64.zip        