name: CICD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh

    env:
      DALAMUD_HOME: /tmp/dalamud

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v3.2.0
        with:
          versionSpec: '6.*'

      - name: Determine Version
        id: versioning
        uses: gittools/actions/gitversion/execute@v3.2.0

      - name: Download dalamud 
        run: |
          New-Item `
            -Path /tmp/ `
            -ItemType Directory `
            -Force `
            | Out-Null

          Invoke-RestMethod https://goatcorp.github.io/dalamud-distrib/latest.zip `
            -Outfile /tmp/dalamud.zip

          Expand-Archive /tmp/dalamud.zip `
            -DestinationPath /tmp/dalamud

      - name: Build
        run: dotnet build 
          $Env:GITHUB_WORKSPACE/SkipCutscene.sln 
          /p:Configuration=Pack
          /p:AssemblyVersion=${{ GitVersion.AssemblySemVer }}

      - name: Publish
      #   if: ${{ github.event_name != 'pull_request' }}
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        run: |
          cd ${{github.workspace}}/SkipCutscene/bin/Pack/SkipCutscene
          $files = (Get-ChildItem .).Name
          gh release create #{{ GitVersion.MajorMinorPatch }} @files